from pathlib import Path
import pandas as pd, numpy as np, json, re
ROOT=Path(__file__).resolve().parents[1]
DATA=ROOT/'data'; CACHE=ROOT/'local_api'/'cache'; PRE=DATA/'precomputed_sdi_v4'; PEAK=DATA/'precomputed_5_year_peak'
TOP={'scoring_volume':.20,'scoring_efficiency':.18,'creation_playmaking':.18,'rebounding':.105,'defense':.20,'impact_value':.135}
# locked subweights
SUB={
'scoring_volume':{'Primary Scoring Output':(.35,{'PTS_per75':1.0}),'Scoring Composition':(.65,{'FGA_per75':.55,'FTA_per75':.45})},
'scoring_efficiency':{'Overall Efficiency':(.60,{'TS_pct':.25,'rTS':.75}),'Component Efficiency':(.40,{'2P_pct':.5,'3P_pct':.4,'FT_pct':.1})},
'creation_playmaking':{'Creation Output':(.385,{'AST_per75':.8,'AST_pct':.2}),'Ball Security / Creation Cost':(.315,{'AST_TOV':.6,'TOV_pct':.4}),'WOWY Offensive Impact':(.30,{'WOWY_Offense':1.0})},
'rebounding':{'Rebounding Production':(.75,{'ORB_per75':.45,'DRB_per75':.35,'TRB_per75':.2}),'Rebounding Rate':(.25,{'OREB_pct':.45,'DREB_pct':.35,'TRB_pct':.2})},
'defense':{'Defensive Activity':(.35,{'STL_per75':.5,'BLK_per75':.5}),'Defensive Activity Rate':(.25,{'STL_pct':.5,'BLK_pct':.5}),'WOWY Defensive Impact':(.40,{'WOWY_Defense':1.0})},
'impact_value':{'WOWY Overall Impact':(1.0,{'WOWY_Net':1.0})}}

def score_row(r):
    cats={}; cov={}
    for cat,groups in SUB.items():
        gscores=[]; intended=0; observed=0
        for _,(gw,stats) in groups.items():
            intended += gw
            vals=[]
            for stat,sw in stats.items():
                v=r.get(stat,np.nan)
                if pd.notna(v): vals.append((float(v),float(sw)))
            if vals:
                den=sum(w for _,w in vals); gscores.append((sum(v*w for v,w in vals)/den,gw)); observed += gw
        if gscores:
            den=sum(w for _,w in gscores); cats[cat]=sum(v*w for v,w in gscores)/den; cov[cat]=observed/intended
    den=sum(TOP[k] for k in cats)
    total=sum(cats[k]*TOP[k] for k in cats)/den if den else np.nan
    return cats,cov,total

season=pd.read_csv(CACHE/'regular_sdi_v4_wowy_player_seasons.csv',low_memory=False)
season['MP']=pd.to_numeric(season['MP'],errors='coerce').fillna(0)
# season component columns are already percentile-based and WOWY-aware.
# Recompute component scores from the canonical locked weights to guarantee the
# higher-level layers use the same formula rather than stale career/peak caches.
season['WOWY_Offense']=pd.to_numeric(season['WOWY_Offense_Percentile'],errors='coerce')
season['WOWY_Defense']=pd.to_numeric(season['WOWY_Defense_Percentile'],errors='coerce')
season['WOWY_Net']=pd.to_numeric(season['WOWY_Net_Percentile'],errors='coerce')
# Existing category columns were generated by the same formula; retain them but
# recompute with explicit locked weights from the row-level statistics.
catcols=list(TOP)
for cat in catcols:
    vals=[]
    for i,r in season.iterrows():
        c,cv,t=score_row(r)
        vals.append((c.get(cat,np.nan),cv.get(cat,0)))
    season[f'__{cat}']=[x[0] for x in vals]; season[f'__{cat}_cov']=[x[1] for x in vals]

# Career: minutes-weighted aggregation of the canonical season-level component
# evidence, with missing WOWY evidence reducing only the affected component.
career_rows=[]
for pid,g in season.groupby('Player_ID',sort=False):
    g=g.copy(); mp=g['MP'].clip(lower=0)
    if mp.sum()<=0: continue
    qg=float(pd.to_numeric(g.get('G',0),errors='coerce').fillna(0).sum())
    qmp=float(mp.sum())
    # established regular career gate
    if qg < 400 or qmp < 10000: continue
    cats={}; cov={}
    for cat in TOP:
        x=pd.to_numeric(g[f'__{cat}'],errors='coerce'); mask=x.notna() & (mp>0)
        if mask.any():
            cats[cat]=float(np.average(x[mask],weights=mp[mask])); cov[cat]=float(np.average(pd.to_numeric(g.loc[mask,f'__{cat}_cov'],errors='coerce').fillna(0),weights=mp[mask]))
    den=sum(TOP[k] for k in cats); sdi=sum(cats[k]*TOP[k] for k in cats)/den if den else np.nan
    first=g.iloc[0]
    career_rows.append({'Player_ID':pid,'Player':first['Player'],'Career_SDI_v4':sdi,'Qualifying_Seasons':int(g['SeasonEndYear'].nunique()),'Career_MP':qmp,'Average_SDI_Coverage':sum(TOP[k]*cov.get(k,0) for k in TOP),**{f'Career_{k}':cats.get(k,np.nan) for k in TOP},**{f'Career_{k}_Coverage':cov.get(k,0) for k in TOP},'Career_WOWY_Offense_Percentile':float(np.average(g['WOWY_Offense'].dropna(),weights=mp[g['WOWY_Offense'].notna()])) if g['WOWY_Offense'].notna().any() else np.nan,'Career_WOWY_Defense_Percentile':float(np.average(g['WOWY_Defense'].dropna(),weights=mp[g['WOWY_Defense'].notna()])) if g['WOWY_Defense'].notna().any() else np.nan,'Career_WOWY_Net_Percentile':float(np.average(g['WOWY_Net'].dropna(),weights=mp[g['WOWY_Net'].notna()])) if g['WOWY_Net'].notna().any() else np.nan})
career=pd.DataFrame(career_rows)
career.to_csv(PRE/'regular_career_sdi_v4_wowy.csv',index=False)

# Peak: preserve the canonical five-season window already selected by v10, but
# recalculate SDI from the WOWY-aware season layer for exactly that window.
v10=json.load(open(PEAK/'regular_profile_peaks_authoritative_v10.json'))
peak_rows=[]
season['Season']=season['Season'].astype(str)
for p in v10['players']:
    pid=p['player_id']; years=p['peak_seasons']; g=season[(season.Player_ID.astype(str)==str(pid)) & season.Season.isin(years)].copy()
    if len(g)<5: continue
    mp=g['MP'].clip(lower=0)
    cats={}; cov={}
    for cat in TOP:
        x=pd.to_numeric(g[f'__{cat}'],errors='coerce'); mask=x.notna() & (mp>0)
        if mask.any(): cats[cat]=float(np.average(x[mask],weights=mp[mask])); cov[cat]=float(np.average(pd.to_numeric(g.loc[mask,f'__{cat}_cov'],errors='coerce').fillna(0),weights=mp[mask]))
    den=sum(TOP[k] for k in cats); sdi=sum(cats[k]*TOP[k] for k in cats)/den if den else np.nan
    # raw WOWY values from canonical DARKO source when available
    raw=pd.read_csv(DATA/'wowy_canonical_percentile_layer_v1.csv',low_memory=False)
    raw=raw[(raw.Player.astype(str).str.strip()==str(p['player_name']).strip()) & raw.Season.astype(str).isin(years)].copy()
    wowy={}
    if not raw.empty:
        w=pd.to_numeric(raw['Avg WOWY O-RAPM'],errors='coerce'); d=pd.to_numeric(raw['Avg WOWY D-RAPM'],errors='coerce'); n=pd.to_numeric(raw['Avg WOWY RAPM'],errors='coerce')
        # Weight by season minutes from the canonical season layer where name/season match.
        weights=g.set_index('Season')['MP'].to_dict(); ww=raw['Season'].map(weights).fillna(0)
        for key,ser in [('WOWY_Offense',w),('WOWY_Defense',d),('WOWY_Net',n)]:
            m=ser.notna() & (ww>0)
            wowy[key]=float(np.average(ser[m],weights=ww[m])) if m.any() else np.nan
    stats=dict(p.get('statistics',{}))
    stats.update(wowy)
    # expose the percentile inputs used by SDI
    stats['WOWY_Offense__percentile']=cats.get('creation_playmaking',np.nan)
    peak_rows.append({'player_id':pid,'player_name':p['player_name'],'peak_start_year':p['peak_start_year'],'peak_end_year':p['peak_end_year'],'peak_seasons':years,'peak_sdi':sdi,'total_games':p.get('total_games'),'total_minutes':p.get('total_minutes'),'statistics':stats,'sdi_coverage':sum(TOP[k]*cov.get(k,0) for k in TOP),**{f'peak_SDI_{k}_Coverage':cov.get(k,0) for k in TOP},**{f'peak_SDI_{k}':cats.get(k,np.nan) for k in TOP}})
peak={'formula':'SDI v4 WOWY canonical higher-level rebuild; canonical five-season window; minutes-weighted component evidence across the selected five qualifying seasons','top_level_weights':TOP,'selection_rules':v10['selection_rules'],'context':'Regular Season','player_count':len(peak_rows),'players':peak_rows,'version':'regular_5_year_peak_wowy_canonical_v1'}
json.dump(peak,open(PEAK/'regular_profile_peaks_wowy_canonical_v1.json','w'),indent=2)
pd.DataFrame([{'player_id':x['player_id'],'player_name':x['player_name'],'peak_start_year':x['peak_start_year'],'peak_end_year':x['peak_end_year'],'peak_sdi':x['peak_sdi'],'peak_sdi_percentile':np.nan,'total_games':x['total_games'],'total_minutes':x['total_minutes'],'peak_seasons':'|'.join(x['peak_seasons']),**{k:v for k,v in x['statistics'].items()}} for x in peak_rows]).to_csv(PEAK/'regular_profile_peaks_wowy_canonical_v1.csv',index=False)

# report key validations
for name in ['Wilt Chamberlain','Michael Jordan','LeBron James','Nikola Jokic']:
 c=career[career.Player.str.casefold()==name.casefold()]
 pk=[x for x in peak_rows if x['player_name'].casefold()==name.casefold()]
 print(name,'career',c[['Career_SDI_v4','Career_defense','Career_impact_value','Career_WOWY_Defense_Percentile','Career_WOWY_Net_Percentile']].to_dict('records') if not c.empty else None,'peak',[(x['peak_start_year'],x['peak_end_year'],x['peak_sdi'],x['statistics'].get('WOWY_Offense'),x['statistics'].get('WOWY_Defense'),x['statistics'].get('WOWY_Net')) for x in pk])

(Path(DATA)/'SDI_V4_WOWY_CAREER_PEAK_BUILD_REPORT_V1.json').write_text(json.dumps({'career_rows':len(career),'peak_rows':len(peak_rows),'formula':'locked SDI v4 weights with WOWY integrated into Creation/Playmaking, Defense, Impact/Value','headshot_policy':'NBA CDN plus project-added verified headshots only; no Basketball-Reference URLs'},indent=2))
